mode:
  nni: false

data:
  path: ./data
  dataset: sider
  num_bond_features: 2
  num_atom_features: 2
  num_workers: 8

model:
  backbone: seq # seq, gnn 
  gnn:
    pretrained: "./data/pretrained/masking.pth" #./data/pretrained/contextpred.pth
    gnn_type: gin   #gin, gcn, graphsage, gat
    num_layer: 5
    emb_dim: 300
    JK: sum  # how the node features across layers are combined. last, sum, max or concat
    dropout_ratio: 0.1
    graph_pooling: sum  # graph level pooling (sum, mean, max, set2set, attention)
    JK_coo_attention: max
  seq:
    pretrained: "./data/pretrained/ChemBERTa-zinc-base-v1"


meta:
  num_atoms: 119
  selfsupervised_weight: 0
  contrastive_weight: 1
  alpha_s: 1
  alpha_e: 0.2 
  beta: 0.01

train:
  random_seed: 42
  epochs:  1
  batch_size: 32
  lr: 3e-4
  meta_lr: 3e-4
  update_lr: 3e-4
  lr_scale: 1  # 'relative learning rate for the feature extraction layer (default: 1)'
  lr_decay_ratio: 0.98
  decay: 0
  update_step: 1
  update_step_test: 1
  eval_epoch: 1

tasks:
  name: sider
  tox21:
    num_tasks: 12
    num_train_tasks: 9
    num_test_tasks: 3
    n_way: 2
    m_support: 2
    k_query: 2
  sider:
    num_tasks: 12
    num_train_tasks: 9
    num_test_tasks: 3
    n_way: 2
    m_support: 2
    k_query: 2


logger:
  log: false
  log_dir: outputs
  mlflow:
    MLFLOW_TRACKING_URI: http://127.0.0.1:8889
    MLFLOW_EXPERIMENT_NAME: "FSADMET"
    REGISTERED_MODEL_NAME: "fsadmet"
