mode:
  nni: false

data:
  path: ./data
  dataset: sider
  num_bond_features: 2
  num_atom_features: 2
  num_workers: 8

model:
  backbone: gnn # seq, gnn
  gnn:
    pretrained: "./data/pretrained/masking.pth" #./data/pretrained/contextpred.pth
    gnn_type: gin #gin, gcn, graphsage, gat
    num_layer: 5
    emb_dim: 300
    JK: max # how the node features across layers are combined. last, sum, max or concat
    dropout_ratio: 0.1
    graph_pooling: max # graph level pooling (sum, mean, max, set2set, attention)
    JK_coo_attention: max
  seq:
    pretrained: "./data/pretrained/ChemBERTa-zinc-base-v1"

meta:
  num_atoms: 119
  selfsupervised_weight: 0
  contrastive_weight: 0.1
  alpha_s: 1
  alpha_e: 0.2
  beta: 0.1

train:
  random_seed: 7
  epochs: 3000
  batch_size: 128
  meta_lr: 0.001
  update_lr: 0.01
  decay: 0
  update_step: 1
  update_step_test: 1
  eval_epoch: 50

tasks:
  name: sider
  tox21:
    num_tasks: 12
    train_tasks: [0, 1, 2, 3, 4, 5]
    test_tasks: [6, 7, 8]
    n_way: 2
    m_support: 2
    k_query: 2
  sider:
    num_tasks: 27
    train_tasks:
      [
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
      ]
    test_tasks: [0, 1, 23, 24, 25, 26]
    n_way: 2
    m_support: 10
    k_query: 128

logger:
  log: false
  log_dir: outputs
  mlflow:
    MLFLOW_TRACKING_URI: http://127.0.0.1:8889
    MLFLOW_EXPERIMENT_NAME: "FSADMET"
    REGISTERED_MODEL_NAME: "fsadmet"
