hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%m-%d-%H-%M}
mode:
  ddp: False
  nni: False
train:
  device_ids: [0] # which gpu to use if any (default: 0)
  batch_size: 64
  epochs: 30
  lr: 0.001
  decay: 0
  num_layer: 5
  emb_dim: 300
  dropout_ratio: 0
  mask_rate: 0.8
  mask_edge: False # whether to mask edges or not together with atom
  JK: last # how the node features are combined across layers. last, sum, max or concat
  gnn_type: gin
  random_seed: 0
  num_workers: 8
  dataset:  ./data/chembl_filtered
  output_model_file: pretrained_masking
inference:
  model_path: outputs/2022-11-11/11-14-44/model_step_1_acc_node_0.975
logger:
  log: True
  log_dir: ${hydra:runtime.output_dir}
  log_per_steps: 5
  final_artifact_path: final
