hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%m-%d-%H-%M}
mode:
  ddp: True
  nni: False
train:
  device_ids: [0,1,2,3] #which gpu to use if any (default: 0)
  batch_size: 2048 
  epochs: 30
  lr: 0.001
  decay: 0
  num_layer: 5
  csize: 3 # context size
  emb_dim: 300
  dropout_ratio: 0
  neg_samples: 1 # number of negative contexts per positive context 
  JK: last # how the node features are combined across layers. last, sum, max or concat
  context_pooling: mean # how the contexts are pooled
  mode: cbow # cbow or skipgram
  gnn_type: gin
  random_seed: 0
  num_workers: 8
  dataset: ./data/chembl_filtered
  output_model_file: pretrained_contextpred
inference:
  model_path: outputs/2022-11-11/17-04-58/model_step_1_accuracy_0.634
logger:
  log: True
  log_dir: ${hydra:runtime.output_dir}
  log_per_steps: 5
  final_artifact_path: final

